# Generated by Django 4.2.13 on 2024-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='day',
            field=models.CharField(blank=True, default="<attribute 'day' of 'datetime.date' objects>", max_length=10),
        ),
        migrations.AddField(
            model_name='posts',
            name='month',
            field=models.CharField(blank=True, default="<attribute 'month' of 'datetime.date' objects>", max_length=20),
        ),
        migrations.AddField(
            model_name='posts',
            name='year',
            field=models.CharField(blank=True, default="<attribute 'year' of 'datetime.date' objects>", max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
