# Generated by Django 4.2.13 on 2024-05-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup', '0002_posts_day_posts_month_posts_year_alter_posts_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='day',
            field=models.CharField(blank=True, default=21, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='month',
            field=models.CharField(blank=True, default=5, max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='year',
            field=models.CharField(blank=True, default=2024, max_length=10),
        ),
    ]
