# Generated by Django 4.2.13 on 2024-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup', '0003_alter_posts_day_alter_posts_month_alter_posts_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='day',
            field=models.CharField(default=21, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='year',
            field=models.CharField(default=2024, max_length=10),
        ),
    ]
