# Generated by Django 4.2.13 on 2024-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup', '0004_alter_posts_day_alter_posts_month_alter_posts_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='day',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='posts',
            name='month',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='posts',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
