# Generated by Django 4.2.13 on 2024-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup', '0005_alter_posts_day_alter_posts_month_alter_posts_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=2024)),
                ('month', models.IntegerField(default=5)),
                ('day', models.IntegerField(default=21)),
            ],
            options={
                'verbose_name_plural': 'Streak',
            },
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, default='Proof', max_length=20),
        ),
    ]
