# Generated by Django 4.2.13 on 2024-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup', '0006_streak_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='streak',
            unique_together={('year', 'month', 'day')},
        ),
    ]
